//
//  DateSelectionViewController.h
//  StratPad
//
//  Created by Eric Rogers on August 12, 2011.
//  Copyright 2011 Glassey Strategy. All rights reserved.
//
//  Displays a date picker in a popover adjacent to the given control.

@class MBCalendarButton;

@interface NSDate (DateSelection)

// zeroes the date
-(NSDate*)normalizeDate;

// locale independent for the date selection component popover
- (NSString*)formattedDateForDateSelection;

// locale independent for the date selection component popover, includes the week day
- (NSString*)formattedDateForDateSelectionMessage;

@end

@protocol DateSelectionDelegate <NSObject>
@required

// called when the user tries to commit a proposed date for a given field (button)
// receiver should update model with new date; the MBCalendarButton.lblDate will be updated by the controller
// the date provided is generated by suggestedDateForCalendarButton:proposedDate:
- (void)dateSelected:(NSDate*)date forCalendarButton:(MBCalendarButton*)button;

// check to see if the proposed date is valid for the given field (button)
- (BOOL)isValid:(NSDate*)date forCalendarButton:(MBCalendarButton*)button;

// the user has proposed a date, so based on that, what is the suggested date for the field (button) in question?
// before the user proposes a date, we suggest the current date
- (NSDate*)suggestedDateForCalendarButton:(MBCalendarButton*)button proposedDate:(NSDate*)proposedDate;

@optional

// if the date is invalid, tell us why; nil if the date is valid
- (NSString*)messageForDate:(NSDate*)date forCalendarButton:(MBCalendarButton*)button isValid:(BOOL)isValid;

@end


@interface MBDateSelectionViewController : UIViewController<UIPopoverControllerDelegate> {
 @private
    UIDatePicker *datePicker_;
    
    MBCalendarButton *button_;
    NSString *title_;
    
    UIPopoverController *popoverController_;    
    
    id<DateSelectionDelegate> delegate_;
    
    UILabel *lblDateSelected_;
    UIBarButtonItem *barButtonTitle_;
    UIColor *normalStatusColor_;
    
}

@property(nonatomic, retain) IBOutlet UIDatePicker *datePicker;
@property(nonatomic, assign) id<DateSelectionDelegate> delegate;

@property(nonatomic,retain) IBOutlet UILabel *lblDateSelected;
@property(nonatomic,retain) IBOutlet UIBarButtonItem *barButtonTitle;
@property (retain, nonatomic) IBOutlet UIBarButtonItem *barButtonNext;

- (id)initWithCalendarButton:(MBCalendarButton*)button andTitle:(NSString*)title;

- (void)showDatePicker;
- (void)hideDatePicker;

- (IBAction)valueChanged;

- (IBAction)clear;
- (IBAction)next;

@end
